#define 🥵 endl
#define 🙋🥿👙 (
#define 🍤🍤👐 )
#define ⱱ⼿ {
#define Ⅹⲵ }
#define 🍓🥌🛒🥿🥄 [
#define 🔱🍍🎸 ]
#define 🧓 ascii_text
#define 💄 void
#define 👑🌾 cout
#define 🐠📗🤧🌷 string
#define 🐏iguo using
#define 🥙🍤🌾 namespace
#define ⒕ⶹ  std
#define ⷌ ;
#define 🪂👷🎑 input
#define 🧤🎐🌔🚷😫🌘👄 <<
#define 🦚 "Enter"
#define 🥣 "text"
#define 🛵🛺 getline
#define 💜 cin
#define 🐣 input
#define 🙄 ,
#define 🍬🪑 for
#define 🧞 int
#define 🦛 i
#define 📠 =
#define 🌓 0
#define ⓑ <
#define 🛀 .
#define 🔆 size
#define 📯 ++
#define 🔜 if
#define 😌🥮 ==
#define 👼🚳 ||
#define 🍁libjiz main
#define 🌂 return
